### ISSUE TITLE
Release new version to include latest patch?

### ISSUE THREAD

**Issue by jorgemanrubia** [ruby/zlib#23]
We were hit by [this bug](https://bugs.ruby-lang.org/issues/10961) that got recently fixed by https://github.com/ruby/zlib/pull/22. Would it be possible to make a new release including it? 

I pushed [this gem](https://rubygems.org/search?query=zlib-basecamp-patch) for our case as a temporary measure, but it would be great to be able to use the official one.

By the way, thanks so much to @wanabe for fixing this one 🙏. The possibility of `zlib` silently writing corrupted data is a serious one and, depending on the scenario, can cause data-loss.

**Comment by hsbt** [comment]
I'm considering to release it before releasing Ruby 3.0.1.
