### ISSUE TITLE
GzipReader does not read concatenated gzip files

### ISSUE THREAD

**Issue by AlexMooney** [ruby/zlib#7]
According to the [gzip docs](https://www.gnu.org/software/gzip/manual/html_node/Advanced-usage.html), concatenated gzip files should decompress the same as a single gzip made from the concatenated contents of the files.

Using GzipReader, only the first gzip member is decompressed.  I've made a [gist](https://gist.github.com/AlexMooney/2e933a0c89ed905669c066c2e78f082f) which reproduces the problem.

**Comment by Vince-Smith** [comment]
[This issue](https://bugs.ruby-lang.org/issues/9790) is 6 years old at this point. A patch was presented and subsequently rejected. I don't get it, there are legitimate use cases for this feature even if they aren't that common.

**Comment by jeremyevans** [comment]
matz rejected my idea for `Zlib::GzipReader.each_file`.  I've offered an alternative approach that adds `Zlib::GzipReader.zcat` in #13.  It will be discussed at the next Ruby developer meeting.

**Comment by jeremyevans** [comment]
`Zlib::GzipReader.zcat` has been added by e2ce56de7d8918099da8a4b5359d46a519d22e63 to meet this need.
